:PROPERTIES:
:ID:       176814ac-f1a6-4033-b96d-5674b9df684a
:END:
#+title: unicode

Unicode is a text encoding standard maintained by the Unicode Consortium. It is designed to support the use of text in all of the world's major writing systems.

* Explanation

The unicode standard is a universal character encoding standard used for the visual representation of text in computer processing. For example, when you strike the key "T", the computer encodes this as U+0054. Text processors then use this number as an index to find an image of a "T", which is drawn on the monitor.

Each character (referred to as code element) is represented by a single number (a code point). In text, code points are listed in [[id:accf6ae8-7296-403c-aaf9-caed90dae25d][hexadecimal]] form, following the prefix "U+". The code point U+0041 is the hexadecimal number, 0041 (decimal number 65). This represents the character "A" in the unicode standard.


* UTF-8
As of 2024, the most prominent unicode character set is UTF-8, which is the HTML standard.

UTF-8 is a variable-length character encoding (such that each character can be 1 to 4 bytes long) and is backwards compatible with ASCII.

Notably, R uses UTF-8 as a default as well

Also note that ASCII is a subset of UTF-8
