:PROPERTIES:
:ID:       6bf8ab89-eb80-4e4e-b365-7ca4a8a4ce20
:END:
#+title: regression tree

CART (Classification and Regression Tree) is a predictive algorithm used in machine learning.

Each root represnts a single input variable, and a split point on that variable. The leaf nodes of the tree contain an output variable used to make a prediction.

* Simple example

For example, given a dataset with two inputs(x) of height and weight, the output is a prediction of male or female sex. The tree can be stored as a graph or a set of rules:

```
# graph
                 [Height > 180 cm]
                     /      \
                [Male]   [Height <= 180 cm]
                                /      \
                         [Weight > 80 kg]
                              /      \
                          [Male]  [Female]



# rules
if height > 180 then MALE
if height <= 180 AND weight > 80 then MALE
if height <= 180 and weight <= 80 then FEMALE
```

Given a new input, the tree is traversed by evaluating the specific input started at the root node of the tree.

* Decision Tree Types

** Classification/Decision tree

Tree used to determine class that the target variable is most likely to fall into

** Regression tree

Predict continuous variable's value. In this case, the regression tree partitions the feature space into regions, and assigns a range for the predicted y value in each region. For example, instead of predicting gender from height and weight, one might predict weight ranges from height and gender.

In this case, the decision tree for the male branch might look like this

```
                        [Gender = Male]
                        /            \
            [Height <= 165]      [Height > 165]
               /       \                  /        \
  [Weight_pred <= 60]  [Weight_pred <= 70]    [Weight_pred > 70]
```

* References
https://bookdown.org/taylordunn/islr-tidy-1655226885741/tree-based-methods.html
