:PROPERTIES:
:ID:       dd117f31-5e67-482d-bb1f-b7ee598689dd
:END:
#+title: lerderderg

Lerderderg state park is a park located North West of Melbourne, with great [[id:545e01d2-e126-4867-9f7c-814a7983062e][hiking trails]]

* Hiking

For a short hike, you can head to Graham's Dam from Mackenzies Flat (where the parking is). This should take around 30 minutes each way, and is an easy walk with two river crossings.

For a harder hike, you can cross the river again on the other side of Graham's Dam, and follow the signs up to the Blackwood Ranges Link track. This will involve some very steep climbing so come prepared. When I did this hike I made it some distance before deciding to turn back (just past LER 504 on the map). In theory, one could continue and turn left when reaching the Blackwood track in order to loop back and return to Graham's dam, but this likely would take 3-4 hours.

* Misc

This is a popular spot for dipping into the water on a sunny day. It could be worth taking some bathers to have a dip after the hike.

* Information

Lerderderg state park follows the Lerderderg river, which eventually feeds into the Werribee River which in turn feeds into Port Phillip bay.
