:PROPERTIES:
:ID:       c04660eb-b167-4383-a791-40cd958c563b
:END:
#+title: mentors

What I have learned from various mentors

* Andre

There are no right or wrong decisions, just the decision you make and have to live with.

* Angela Baker

The importance of being organised, getting things in on time.

The importance of communicating clearly and reducing the amount of work required for people whose advice you are seeking.

The RACI model (Responsibility, Accountability, Consulted, Informed)

* Cynthia Kim

The importance of work-life balance

The importance of forming good relationships with people

* Danny Smith

The importance of high quality work, and providing constructive criticism to those who need it when work is not up to standard.

* Kinto Behr

The importance of not having an ego when thinking about one's own work; only striving to improve and genuinely seek feedback.

The importance of breaking a problem down in order to truly understand what the issues are, and to understand what you are dealing with

* Ben Desta

The importance of work life balance and caring for your people. The importance of being practical.
